### ISSUE TITLE
Can i catch redis connect exception by code

### ISSUE THREAD

**Issue by cyssxt** [rmax/scrapy-redis#96]
By scrapy,I have two spiders,one is a common spider by start_urls array,another is Redis spider!
when my redis is not start,My first common spider can not run successfully!Can i do something to sovle it !

**Comment by n1kt0** [comment]
More information would be useful, it is not clear to me how they are depending on each other?

**Comment by kingname** [comment]
Because when you start a scrapy project, all file in the `spiders` folder will be executed. Just like when you import a Python's package, the code in the imported file will be execute, the Spider class must be loaded so that Scrapy can find it.

This is not the business of scrapy_redis, it due to the the mechanism of Scrapy.
